<a href="https://colab.research.google.com/github/rajgupta-github/DeepLearning-with-Python/blob/master/TensorFlow/Learn_TF2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# !pip install tensorflow-gpu
# !pip install tf-nightly-gpu
# !pip uninstall tf-nightly

In [0]:
import tensorflow as tf
import datetime
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%load_ext tensorboard

from google.colab import drive
drive.mount('/content/drive')

In [0]:
x=tf.Variable(3)
y=tf.Variable(5)
z=x+y
print(z)

In [0]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_lables) = fashion_mnist.load_data()
model = tf.keras.Sequential([
         tf.keras.layers.Flatten(input_shape=(28,28)),
         tf.keras.layers.Dense(128, activation="relu"),
         tf.keras.layers.Dense(10, activation="softmax"),
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

log_dir= "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(train_images, train_labels, epochs=5, callbacks = [tensorboard_callback])
%tensorboard --logsdir logs/fit


First Simple Single Neuron Neural Network to predict Fahreheight from Celsius Data

In [0]:
temp_df = pd.read_csv('/content/drive/My Drive/TensorFlow/Celsius_to_Fahrenheit.csv')
temp_df.head()
temp_df.describe(include="all")
temp_df.info()
sns.scatterplot(x='Celsius', y='Fahrenheit', data=temp_df)
X_train = temp_df['Celsius']
y_train = temp_df['Fahrenheit']
X_train.shape
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=1, input_shape=[1]))
model.summary()
model.compile(optimizer=tf.keras.optimizers.Adam(), loss = "mean_squared_error")
epoch_hist = model.fit(X_train, y_train, epochs=2000)

# plt.figure(figsize=(16,10))
plt.plot(epoch_hist.history['loss'])
plt.title("Model Loss during training")
plt.xlabel("#Epochs")
plt.ylabel("Training Loss")
plt.legend(["Training Loss"])
model.get_weights()

Temp_C = 100
Temp_F = model.predict([Temp_C])
print('Temperature in degF Using Trained ANN =', Temp_F)

# Let's confirm this Using the equation: 
Temp_F = 9/5 * Temp_C + 32
print('Temperature in degF Using Equation =', Temp_F)

**`Mini Neural Network to predict Ice cream Sales`**

Model 1 with 1 hidden layer

In [0]:
sales_df = pd.read_csv('/content/drive/My Drive/TensorFlow/SalesData.csv')
display(sales_df.head())
display(sales_df.describe(include="all"))
display(sales_df.info())
# display(sns.scatterplot(x='Temperature', y='Revenue', data=sales_df))
X_train = sales_df['Temperature']
y_train = sales_df['Revenue']
X_train.shape
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=1, input_shape=[1]))
model.summary()
model.compile(optimizer=tf.keras.optimizers.Adam(), loss = "mean_squared_error")
epoch_hist = model.fit(X_train, y_train, epochs=2000)
epoch_hist.history.keys()
# plt.figure(figsize=(16,10))
plt.plot(epoch_hist.history['loss'])
plt.title("Model Loss during training")
plt.xlabel("#Epochs")
plt.ylabel("Training Loss")
plt.legend(["Training Loss"])


Temp_Temperature = 40
Temp_Revenue = model.predict([Temp_Temperature])
print('Revenue of Ice Cream Using Trained ANN =', Temp_Revenue)

model.get_weights()

sns.scatterplot(X_train, y_train, color="grey")
plt.plot(X_train, model.predict(X_train), color="red")
plt.title("Revenue Prediction at a given temperature")
plt.xlabel("Temperature")
plt.ylabel("Revenue in Dollars")


Model 2 with 2 hidden layers

In [0]:
sales_df = pd.read_csv('/content/drive/My Drive/TensorFlow/SalesData.csv')
display(sales_df.head())
display(sales_df.describe(include="all"))
display(sales_df.info())
# display(sns.scatterplot(x='Temperature', y='Revenue', data=sales_df))
X_train = sales_df['Temperature']
y_train = sales_df['Revenue']
X_train.shape
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=10, input_shape=[1]))
model.add(tf.keras.layers.Dense(units=1))
model.summary()
model.compile(optimizer=tf.keras.optimizers.Adam(), loss = "mean_squared_error")
epoch_hist = model.fit(X_train, y_train, epochs=500)
epoch_hist.history.keys()
# plt.figure(figsize=(16,10))
plt.plot(epoch_hist.history['loss'])
plt.title("Model Loss during training")
plt.xlabel("#Epochs")
plt.ylabel("Training Loss")
plt.legend(["Training Loss"])


Temp_Temperature = 40
Temp_Revenue = model.predict([Temp_Temperature])
print('Revenue of Ice Cream Using Trained ANN =', Temp_Revenue)

model.get_weights()

sns.scatterplot(X_train, y_train, color="grey")
plt.plot(X_train, model.predict(X_train), color="red")
plt.title("Revenue Prediction at a given temperature")
plt.xlabel("Temperature")
plt.ylabel("Revenue in Dollars")


Using Scikit Learn, Linear Regression compare with Model 1

In [61]:
# Using Model 1 ANN
Temp_Temperature = 40
Temp_Revenue = model.predict([Temp_Temperature])
print('Revenue of Ice Cream Using Trained ANN =', Temp_Revenue)

Revenue of Ice Cream Using Trained ANN = [[914.6109]]


In [75]:
model.get_weights()

[array([[22.252516]], dtype=float32), array([24.510231], dtype=float32)]

In [66]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV
parameters = {
                'normalize':[True,False], 
                'copy_X':[True, False], 
                'fit_intercept':[True,False]
             }
linreg = LinearRegression() # this the model on which i would want to experiment 
# Call the GridSearch Class, Pass the model and parameter 
linreg = GridSearchCV(linreg,parameters)
linreg.estimator



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
linreg = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [69]:
X_train.shape
y_train.shape

(500, 1)

In [70]:
X_train = X_train.values.reshape(-1,1)

AttributeError: ignored

In [0]:
y_train = y_train.values.reshape(-1,1)

In [0]:
linreg.fit(X_train, y_train)
y_pred_test = linreg.predict(X_train)

In [72]:
linreg.predict([[40]])

array([[902.57628752]])

In [74]:
display(linreg.coef_)
display(linreg.intercept_)

array([[21.44362551]])

array([44.83126709])